### ISSUE TITLE
provide .go-base.yaml.example pls

### ISSUE THREAD

**Issue by putrarifin** [dhax/go-base#13]
hello dhax and team, nice project. but i confuse for adding .go-base.yaml without example. its really nice to have if u prodive it. thanks

**Comment by dhax** [comment]
Hi, please have look at this issue here: https://github.com/dhax/go-base/issues/2

There are good reasons, mainly security, not to have this committed into your git repository. All possible configs are listed in the Readme, you only need to overwrite the ones you want to change.
