### ISSUE TITLE
dgrijalva/jwt-go is no longer maintained

### ISSUE THREAD

**Issue by hyperyuri** [dhax/go-base#17]
The new repository is https://github.com/golang-jwt/jwt

Can I update the package to the new one?
If yes, please assignee this issue for me and will send the pull request

**Comment by hyperyuri** [comment]
I was checking the source code and actually the github.com/go-chi/jwtauth don't use this package anymore too.

now they are using https://github.com/lestrrat-go/jwx and not (dgrijalva/jwt-go or golang-jwt/jwt)

**Comment by dhax** [comment]
hey there, thanks a lot for the pull request! As I was already trying to update all packages including chi, so this should be good now. Tanks again!

**Comment by hyperyuri** [comment]
You are welcome! Great job with this boilerplate! 🚀
