### ISSUE TITLE
Request: Can we get a write up on why this folder structure is setup the way it is?

### ISSUE THREAD

**Issue by sans-clue** [dhax/go-base#24]
Hi, is it possible to get a write up, a video, or some kind of additional information on why the project is structured this way?

For example, I see multiple bun/model files existing in different places, `auth/pwdless/account.go`, `models/profile.go`, etc.
And if I wanted to add more resources or endpoints, I don't quite understand where to start. 

This project doesn't seem to follow any design that I'm previously familiar with and I would very much like to learn it.

If the author or someone knowledgeable in this community could point us to a guide or something, that would be very much appreciated. This could help newbies to Go apply this design pattern to their own projects.

Thank you!

**Comment by dhax** [comment]
Hi there,
this project basically follows the [chi router rest example](https://github.com/go-chi/chi/tree/master/_examples/rest)

The rest is mainly what worked for me at that time :)
I decided to put the authentication specific model into the auth package, the other models should be application specific and reside in the models folder.
The API router splits the api into admin and user api routes and the folder structure basically follows that pattern.

You can have a look at this [PR here](https://github.com/dhax/go-base/pull/11/files) how you would add new models with according routes.

Hope that helps, feel free to ask if something is unclear.
