### ISSUE TITLE
how to start

### ISSUE THREAD

**Issue by DevJoseWeb** [dhax/go-base#3]
dev@dev-x:~$ cd Documentos
dev@dev-x:~/Documentos$ cd go-base
dev@dev-x:~/Documentos/go-base$ go build   OK
dev@dev-x:~/Documentos/go-base$ go run main.go
A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.

Usage:
  go-base [command]

Available Commands:
  gendoc      Generate project documentation
  help        Help about any command
  migrate     use go-pg migration tool
  serve       start http server with configured api

Flags:
      --config string   config file (default is $HOME/.go-base.yaml)
      --db_debug        log sql to console
  -h, --help            help for go-base

Use "go-base [command] --help" for more information about a command.
dev@dev-x:~/Documentos/go-base$ go-base migrate init
go-base: comando não encontrado
dev@dev-x:~/Documentos/go-base$ go-base migrate
go-base: comando não encontrado
dev@dev-x:~/Documentos/go-base$ go-base serve
go-base: comando não encontrado
dev@dev-x:~/Documentos/go-base$

**Comment by dhax** [comment]
Sorry for the late reply. You basically have to follow the steps listed below "Start Application":
- create a postgres database if you haven't already
- build the application executable go build
- create the database tables with go-base migrate init
- run the migrations scripts to populate some data with go-base migrate
- run the http server with go-base serve
