### ISSUE TITLE
need documentation on how to create an env file

### ISSUE THREAD

**Issue by karfianto** [dhax/go-base#9]
It's not clear where to put environment variable DATABASE_URL and other variables when using different config

**Comment by dhax** [comment]
you can use environment variables (recommended as by 12-Factor App) or create a file at $HOME/.go-base.yaml as shown in the help message.

**Comment by dhax** [comment]
also there is no variable DATABASE_URL anymore, it's split up into its single parts now, check the Env Var section. Updated the Readme on this, sorry for the confusion.
